package pt.utl.ist.lucene.utils;

import org.apache.log4j.Logger;
import org.dom4j.DocumentException;
import pt.utl.ist.lucene.utils.temporal.TimeExpression;
import pt.utl.ist.lucene.utils.temporal.tides.TimexesDocument;
import pt.utl.ist.lucene.utils.temporal.tides.Timex2TimeExpression;
import pt.utl.ist.lucene.utils.nlp.SentenceSpliter;
import pt.utl.ist.lucene.utils.placemaker.PlaceMakerDocument;
import pt.utl.ist.lucene.treceval.geotime.NyTimesDocument;

import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

/**
 * @author Jorge Machado
 * @date 28/Dez/2009
 * @time 16:54:03
 * @email machadofisher@gmail.com
 */
public class DocumentPlaceMakerAndTemporalSentences {

    private static Logger logger = Logger.getLogger(DocumentPlaceMakerAndTemporalSentences.class);

    NyTimesDocument document;
    String text;
    List<PlaceMakerAndTemporalSentence> placemakerTemporalSentences;
    TimexesDocument timexesDocument;
    PlaceMakerDocument placeMakerDocument;

    /**
     * Creates a List of sentences with time expressions
     * @param document
     * @param timexesDocument document with timexes generated by ILPS TIMEXTAG using TIDES notation
     * @see "http://fofoca.mitre.org/annotation_guidelines/2005_timex2_standard_v1.1.pdf"
     */
    public DocumentPlaceMakerAndTemporalSentences(NyTimesDocument document,  TimexesDocument timexesDocument, PlaceMakerDocument placeMakerDocument)
    {
        init(document,timexesDocument,placeMakerDocument);
    }

    public DocumentPlaceMakerAndTemporalSentences(NyTimesDocument document,  String timexesXml,String placeMakerDocumentXml) throws DocumentException
    {
        TimexesDocument timexesDocument = new TimexesDocument(timexesXml);
        PlaceMakerDocument placeMakerDocument = new PlaceMakerDocument(placeMakerDocumentXml);
        init(document,timexesDocument,placeMakerDocument);
    }



    public void init(NyTimesDocument document,  TimexesDocument timexesdocument, PlaceMakerDocument placeMakerDocument)
    {

        this.text = document.getSgmlWithoutTags();
        placemakerTemporalSentences = (List<PlaceMakerAndTemporalSentence>) SentenceSpliter.split(text, PlaceMakerAndTemporalSentence.class);
        this.timexesDocument = timexesdocument;
        this.placeMakerDocument = placeMakerDocument;

        if(placeMakerDocument != null && placeMakerDocument.getPlaceDetails() != null && placeMakerDocument.getPlaceDetails().size() > 0)
        {
            for(PlaceMakerDocument.PlaceDetails placeDetails : placeMakerDocument.getPlaceDetails())
            {
                if(placeDetails.getRefs() != null)
                {
                    for(PlaceMakerDocument.PlaceRef placeRef : placeDetails.getRefs())
                    {
                        int startOffset = document.toStringOffset2txtwithoutTagsOffset(placeRef.getStartOffset());
                        //todo meter as place nas geotemporalsentences
                        for(PlaceMakerAndTemporalSentence placeMakerAndTemporalSentence : placemakerTemporalSentences)
                        {
                            if(startOffset >= placeMakerAndTemporalSentence.getStartOffset() && startOffset < placeMakerAndTemporalSentence.getEndOffset())
                            {
                                placeMakerAndTemporalSentence.getPlaceRefs().add(placeRef);
                                break;
                            }
                        }
                    }
                }
            }
        }
        if(this.timexesDocument != null && this.timexesDocument.getTimex2TimeExpressions() != null && this.timexesDocument.getTimex2TimeExpressions().size()>0)
        {
            Iterator<Timex2TimeExpression> timexExpressionSetIter = this.timexesDocument.getTimex2TimeExpressions().iterator();
            Timex2TimeExpression timex2TimeExpressionsList = timexExpressionSetIter.next();

            if(placemakerTemporalSentences != null)
            {
                for(PlaceMakerAndTemporalSentence temporalSentence : placemakerTemporalSentences)
                {
                    while(timex2TimeExpressionsList.getTimeExpressions().size() == 0)
                    {
                        if(timexExpressionSetIter.hasNext())
                            timex2TimeExpressionsList = timexExpressionSetIter.next();
                        else
                        {
                            timex2TimeExpressionsList = null;
                            break;
                        }
                    }
                    if(timex2TimeExpressionsList == null)
                        break;
                    if(timex2TimeExpressionsList.getStartOffset() >= temporalSentence.getEndOffset())
                    {
                        //go to next sentence
                    }
                    else
                    {
                        while(timex2TimeExpressionsList.getStartOffset() >= temporalSentence.getStartOffset() && timex2TimeExpressionsList.getEndOffset() <= temporalSentence.getEndOffset())
                        {
                            temporalSentence.getTimexes().add(timex2TimeExpressionsList);
                            if(timexExpressionSetIter.hasNext())
                                timex2TimeExpressionsList = timexExpressionSetIter.next();
                            else
                            {
                                break;
                            }
                        }
                    }
                }
            }
        }
    }


    public List<Timex2TimeExpression> getTimex2TimeExpressionsSets() {
        return timexesDocument.getTimex2TimeExpressions();
    }

    /**
     *
     * @return found sentences with temporal expressions
     */
    public List<PlaceMakerAndTemporalSentence> getSentences()
    {
        return placemakerTemporalSentences;
    }


    public List<TimeExpression> getAllNormalizedTimeExpressions()
    {
        if(placemakerTemporalSentences != null && placemakerTemporalSentences.size()>0)
        {
            List<TimeExpression> expressions = new ArrayList<TimeExpression>();
            for(PlaceMakerAndTemporalSentence s: placemakerTemporalSentences)
                expressions.addAll(s.getAllTimeExpressions());
            return expressions;
        }
        else
            logger.error("Document with 0 sentences");
        return null;
    }

    public List<String> getAllNLTimeExpressions()
    {
        if(placemakerTemporalSentences != null && placemakerTemporalSentences.size()>0)
        {
            List<String> expressions = new ArrayList<String>();
            for(PlaceMakerAndTemporalSentence s: placemakerTemporalSentences)
                expressions.addAll(s.getAllNLExpressions());
            return expressions;
        }
        else
            logger.error("Document with 0 sentences");
        return null;
    }


    public NyTimesDocument getDocument() {
        return document;
    }

    /**
     *
     * @return TEXT without tags
     */
    public String getText() {
        return text;
    }

    public String toString()
    {
        String txt = "REFTIME: " + timexesDocument.getRefTime() +"\n";
        for(PlaceMakerAndTemporalSentence s: getSentences())
        {
            txt += s;
        }
        return txt;
    }
}
